name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install requirements
        run: |
          python -m pip install -r requirements.txt

      - name: Install package
        run: |
          python -m pip install -e .

      - name: Run unit tests
        run: |
          pytest -q tests/unit

      - name: Run vector_db tests
        run: |
          pytest -q tests/vector_db

      - name: Run tslearn tests
        run: |
          pytest -q tests/tslearn

      - name: Run model_runner tests
        run: |
          pytest -q tests/model_runner

      - name: Run llm tests
        run: |
          pytest -q tests/llm

      - name: Run torch tests
        run: |
          pytest -q tests/torch

      - name: Run integration tests (if any)
        run: |
          if [ -d tests/integration ]; then pytest -q tests/integration; else echo 'No integration tests'; fi

  integration-tests:
    needs: run-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install requirements
        run: |
          python -m pip install -r requirements.txt

      - name: Install package
        run: |
          python -m pip install -e .

      - name: Run integration tests
        run: |
          pytest -q tests/integration
